version: '3.8'

services:
  go-sse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Optional Nginx for SSL termination and load balancing
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - go-sse
    restart: unless-stopped
    # Uncomment to enable nginx (you'll need to create the config files)
    profiles: ["with-nginx"]

  # Example client web server for testing
  test-client:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./examples:/usr/share/nginx/html:ro
    restart: unless-stopped
    # Run this service only when explicitly requested
    profiles: ["with-client"]
