# nixpacks.toml configuration for go-sse with MongoDB support

[phases.setup]
aptPkgs = ["make", "gcc", "git"]

[phases.build]
cmds = [
  "go mod download",
  "go build -o bin/go-sse ./cmd/server"
]

[start]
cmd = "./bin/go-sse"

[variables]
PORT = "8080"
STORE_TYPE = "mongo"
MONGO_URI = "$MONGO_URI"
MONGO_DB_NAME = "$MONGO_DB_NAME"
MONGO_COLLECTION = "$MONGO_COLLECTION"
MONGO_DOCUMENT_ID = "$MONGO_DOCUMENT_ID"
MAX_REQUEST_SIZE_MB = "20"

# Health check configuration
[healthcheck]
cmd = "curl -f http://localhost:$PORT/health || exit 1"
interval = "30s"
timeout = "5s"
retries = 3
startPeriod = "10s"
